#!/usr/bin/env bash

# build all services that have been modified
if [ -n "$GITLAB_PERSONAL_TOKEN" ]; then
    docker login registry.gitlab.com -u alienspaces@gmail.com -p "$GITLAB_PERSONAL_TOKEN"
fi

if [ -n "$CI_REGISTRY_USER" ] && [ -n "$CI_REGISTRY_PASSWORD" ]; then
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
fi

# previous latest commit present on a branch before a merge
# request. Only populated when there is a merge request
# associated with the pipeline.
PREV_COMMIT=$CI_COMMIT_BEFORE_SHA
if [ -z "$PREV_COMMIT" ]; then
    # otherwise use the actual previous commit
    PREV_COMMIT=$(git rev-parse HEAD^)
fi

# service directory list
SERVICE_NAMES=(game)

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    SERVICE_DIR="./service/$SERVICE_NAME"
    echo "Directory: $SERVICE_DIR";
    echo ""
    ls -la

    # build if anything changed in common
    CHANGED=$(git diff "$PREV_COMMIT" --name-only .gitlab-ci.yml ./core ./build ./script/deploy ./script/build)
    if [ -z "$CHANGED" ]; then
        # build if anything changed in the service
        CHANGED=$(git diff "$PREV_COMMIT" --name-only -- "$SERVICE_DIR")
    fi
    if [ -z "$CHANGED" ]; then
        echo "No changes"
        continue
    fi

    echo "Changes detected in $SERVICE_DIR"

    if [ -f "${SERVICE_DIR}/build/docker/Dockerfile" ]; then
        docker build -f "${SERVICE_DIR}/build/docker/Dockerfile" -t "go-mud/${SERVICE_NAME}-server" .
        docker tag "go-mud/${SERVICE_NAME}-server" "registry.gitlab.com/alienspaces/go-mud/${SERVICE_NAME}-server:latest"
        docker push "registry.gitlab.com/alienspaces/go-mud/${SERVICE_NAME}-server:latest"
    fi

done


