#!/usr/bin/env bash

# Opens a psql session to the database specified in current APP environment
# \l              - list schemas
# \c go-boilerplate-template - connect to schema

# Environment
source ${BASH_SOURCE%/*}/environment || exit $?

if [ $status -ne 0 ]; then
    echo "Establishing environment error, cannot continue" >&2
    exit $status
fi

export PGPASSWORD=$APP_SERVER_DB_PASSWORD
psql --host=$APP_SERVER_DB_HOST \
     --port=$APP_SERVER_DB_PORT \
     --username=$APP_SERVER_DB_USER \
     $APP_SERVER_DB_NAME
