#!/usr/bin/env bash

# Environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source "${BASH_SOURCE%/*}"/environment || exit $?
fi

# NOTE: Add new services here
SERVICE_NAMES=(game)
echo "=> (load-seed-data) - Service names " "${SERVICE_NAMES[@]}"

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    # Reset APP_SERVER_PORT as each service should define
    # a unique server port in their local env
    export APP_SERVER_PORT=""

    # Ingoring template
    if [ "$SERVICE_NAME" = "template" ] && [ "$APP_SERVER_ENABLE_TEMPLATE" != 1 ]; then
        echo "=> (load-seed-data) - Skipping database $SERVICE_NAME"
        continue
    fi

    cd "service/${SERVICE_NAME}" || exit

    echo
    echo "=> (load-seed-data) - Loading ${SERVICE_NAME} service seed data"
    echo

    # Environment
    source ../../"${BASH_SOURCE%/*}"/environment || exit $?

    go run ./cmd/cli load-seed-data || exit $?

    cd - || exit

done
