#!/usr/bin/env bash

# Environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source ${BASH_SOURCE%/*}/environment || exit $?
fi

# go version
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "=> Use ${APP_SERVER_GO_VERSION}"
    gvm use $APP_SERVER_GO_VERSION || exit $?
fi

# golang migrate
MIGRATE_PATH=$(which migrate)
if [[ "$MIGRATE_PATH" != *"$APP_SERVER_GO_VERSION"* ]]; then
    source ${BASH_SOURCE%/*}/db-migrate-install || exit $?
fi

if [ -z "$2" ]
then
    echo "ERROR: specify service name and a description"
    echo "Example: ./script/db-migrate-create template create_template_objects"
    exit 1
fi

migrate create -ext sql -dir ./service/$1/migration $2


