#!/usr/bin/env bash

# Environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source ${BASH_SOURCE%/*}/environment || exit $?
fi

# go version
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "=> Use ${APP_SERVER_GO_VERSION}"
    gvm use $APP_SERVER_GO_VERSION || exit $?
fi

# https://github.com/golang-migrate/migrate/releases
go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.14.1
