#!/usr/bin/env bash

# Local development run script

# copy development env
cp .env.development .env

# Environment
source ${BASH_SOURCE%/*}/environment || exit $?

source ${BASH_SOURCE%/*}/db-start || exit $?

source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

source ${BASH_SOURCE%/*}/load-test-data || exit $?
