#!/usr/bin/env bash

# stop krakend
source ${BASH_SOURCE%/*}/krakend-stop || exit $?

# start krakend
docker run --name go-boilerplate-krakend -p 8082:8080 -v "${PWD}:/etc/krakend/" -d devopsfaith/krakend:1.2 run -d -c krakend.json
