#!/usr/bin/env bash

NGINX_RUNNING=$(docker ps -a | grep "go-mud-krakend")
if [[ -n "${NGINX_RUNNING}" ]]; then
    echo
    echo "=> Stopping krakend"
    echo
    docker stop go-mud-krakend
    docker rm go-mud-krakend
fi
