#!/usr/bin/env bash

# stop krakend
source ${BASH_SOURCE%/*}/krakend-stop || exit $?

# check krakend
docker run --name go-boilerplate-krakend -p 8082:8080 -v "${PWD}:/etc/krakend/" devopsfaith/krakend:1.1 check -d -c krakend.json
