#!/usr/bin/env bash

# Environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source "${BASH_SOURCE%/*}"/environment || exit $?
fi

# NOTE: Add new services here
SERVICES=(game)

for SERVICE in "${SERVICES[@]}"; do

    # Reset APP_SERVER_PORT as each service should define
    # a unique server port in their local env
    export APP_SERVER_PORT=""

    # Ingoring template
    if [ "$SERVICE_NAME" = "template" ] && [ "$APP_SERVER_ENABLE_TEMPLATE" != 1 ]; then
        echo "=> (start_service_databases) - Skipping database $SERVICE_NAME"
        continue
    fi

    cd "service/${SERVICE}" || exit

    echo
    echo "** Loading ${SERVICE} service seed data"
    echo

    # Environment
    source ../../"${BASH_SOURCE%/*}"/environment || exit $?

    go run ./cmd/cli load-seed-data || exit $?

    cd - || exit

done
