#!/usr/bin/env bash

# Local development run script

echo
echo "=> Stopping services"
echo

function stop_services {
    for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

        if [ -f "$SERVICE_BASE_PATH/$SERVICE_NAME/.env" ]; then

            # stop server
            SERVER_NAME="go-boilerplate-${SERVICE_NAME}-server"

            echo "=> (stop_services) - Finding process for $SERVER_NAME"

            PID=$(pgrep -f $SERVER_NAME)

            if [ -n "$PID" ]; then
                echo "Killing process $PID for $SERVER_NAME"
                kill $PID
                sleep 2
            fi
        fi
    done
}

# service directory list
shopt -s dotglob
shopt -s nullglob

# Service directory list
SERVICE_BASE_PATH=./service
cd $SERVICE_BASE_PATH
SERVICE_NAMES=(*)
cd -

stop_services

# Service example directory list
if [[ "$APP_SERVER_ENABLE_EXAMPLES" == 1 ]]; then
    echo " => Starting example services"

    SERVICE_BASE_PATH=./service/example
    cd $SERVICE_BASE_PATH
    SERVICE_NAMES=(*)
    cd -

    stop_services
fi
