#!/usr/bin/env bash

# Starts a service running in the background.
# To stop the service run ./script/services-stop-background [service name]

# Local development run script

SERVICE_NAME=$1
if [ -z "${SERVICE_NAME}" ]; then
    echo "=> (start service) Missing service name, cannot start service"
    exit 0
fi

shift

echo
echo "=> (start service) Starting service ${SERVICE_NAME}"
echo

# copy development env
cp .env.development .env

# Environment
source ${BASH_SOURCE%/*}/environment || exit $?

# reset APP_SERVER_PORT as each service should define
# a unique server port in their local env
export APP_SERVER_PORT=""

# build and run service
cd service/$SERVICE_NAME

# NOTE: we shift into the service directory before sourcing
# the environment so $PWD is correct for APP_SERVER_HOME

# copy development env
cp .env.development .env

# add local env (runtime secrets we don't actually want committed to git)
cat .env.local >> .env

# load service specific environment
source ../../${BASH_SOURCE%/*}/environment || exit $?

# build server
SERVER_NAME="go-boilerplate-${SERVICE_NAME}-server"
rm -f $SERVER_NAME
go build -o $SERVER_NAME ./cmd/server || exit $?

echo "Running server $SERVER_NAME"
./$SERVER_NAME&
cd -
