#!/usr/bin/env bash

# Local development run script

# Environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source "${BASH_SOURCE%/*}"/env || exit $?
fi

# stop
source "${BASH_SOURCE%/*}"/services-stop || exit $?

echo
echo "=> Starting services"
echo

function start_services {
    for service_name in "${service_names[@]}"; do

        # Ingoring template
        if [ "$service_name" = "template" ] && [ "$APP_SERVER_ENABLE_TEMPLATE" != 1 ]; then
            echo "=> (start_services) - Skipping service $service_name"
            continue
        fi

        echo "=> (start_services) - Starting service $service_name"

        if [ -f "${service_base_path}/$service_name/.env" ]; then

            # Reset APP_SERVER_PORT as each service should define
            # a unique server port in their local env
            export APP_SERVER_PORT=""

            # Build and run service
            cd "$service_base_path/$service_name" || exit

            # NOTE: we shift into the service directory before sourcing
            # the environment so $PWD is correct for APP_SERVER_HOME

            # Copy development env
            cp .env.development .env

            # Add local env (runtime secrets we don't actually want committed to git)
            cat .env.local >> .env

            # Load service specific environment
            if [ -f "../../${BASH_SOURCE%/*}/env" ]; then
                source ../../"${BASH_SOURCE%/*}"/env || exit $?
            elif [ -f "../../../${BASH_SOURCE%/*}/env" ]; then
                source ../../../"${BASH_SOURCE%/*}"/env || exit $?
            fi

            # Build server
            SERVER_NAME="go-mud-${service_name}-server"
            rm -f "$SERVER_NAME"
            go build -o "$SERVER_NAME" ./cmd/server

            echo "=> (start_services) - Running server $SERVER_NAME - $APP_SERVER_HOST:$APP_SERVER_PORT"
            ./"$SERVER_NAME"&
            cd - || exit
        fi
    done
}

shopt -s dotglob
shopt -s nullglob

# Service directory list
service_base_path=./service
cd $service_base_path || exit
service_names=(*)
cd - || exit

start_services

# Service example directory list
if [[ "$APP_SERVER_ENABLE_EXAMPLES" == 1 ]]; then
    echo
    echo " => Starting example services"
    echo

    service_base_path=./service/example
    cd $service_base_path || exit
    service_names=(*)
    cd - || exit

    start_services
fi
