#!/usr/bin/env bash

# Local development run script

SERVICE_NAME=$1
if [ -z "${SERVICE_NAME}" ]; then
    echo "=> (start service) Missing service name, cannot start service"
    exit 0
fi

shift

# start nginx
source ${BASH_SOURCE%/*}/start-nginx || exit $?

echo
echo "=> (start service) Starting service ${SERVICE_NAME}"
echo

# copy development env
cp .env.development .env

# Environment
source ${BASH_SOURCE%/*}/environment || exit $?

# server
SERVER_NAME="go-boilerplate-${SERVICE_NAME}-server"

echo "Finding process for $SERVER_NAME"

PID=$(pgrep $SERVER_NAME)

if [ -n "$PID" ]; then
    echo "Killing process $PID for $SERVICE_NAME"
    kill $PID
    sleep 2
fi

