#!/usr/bin/env bash

echo
echo "=> Test client"
echo

# "docker" or "local"
export APP_SERVER_DB_SERVICE=docker
if [ -n "$1" ]; then
    export APP_SERVER_DB_SERVICE=$1
    shift
fi

# Environment
source ${BASH_SOURCE%/*}/environment || exit $?

dir="client"
for f in "$dir"/*; do
    echo "=> Test client directory - $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -cover -count 1 ./... || exit $?
    fi
    cd -
done
