#!/usr/bin/env bash

# copy development env
cp .env.development .env

# Environment
source ${BASH_SOURCE%/*}/environment || exit $?

# go version
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "=> Use ${APP_SERVER_GO_VERSION}"
    gvm use $APP_SERVER_GO_VERSION || exit $?
fi

if ! [[ -n ${APP_SERVER_DB_SERVICE} ]]; then
    echo "=> (test-ci) Missing APP_SERVER_DB_SERVICE"
    exit 1
fi

# start database
source ${BASH_SOURCE%/*}/db-start || exit $?

# migrate database
source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

# test client
source ${BASH_SOURCE%/*}/test-client || exit $?

# test core
source ${BASH_SOURCE%/*}/test-core || exit $?

# test service
source ${BASH_SOURCE%/*}/test-service || exit $?

# stop services
source ${BASH_SOURCE%/*}/db-stop || exit $?
