#!/usr/bin/env bash

# copy ci env
cp .env.ci .env

# Environment
source "${BASH_SOURCE%/*}"/environment || exit $?

# start database
source "${BASH_SOURCE%/*}"/db-start || exit $?

# migrate database
source "${BASH_SOURCE%/*}"/db-migrate-up || exit $?

# test core
source "${BASH_SOURCE%/*}"/test-core || exit $?

# test service
source "${BASH_SOURCE%/*}"/test-service || exit $?
