#!/usr/bin/env bash

# DESCRIPTION:
#   Execute ./service unit tests
# USAGE:
#   Test all services
#     ./script/test-service
#   Test specific service
#     ./script/test-service ./service/example/player

function test_service {
    test_function_name=$1

    if [ -f "go.mod" ]; then
        echo "=> (test-service) Test service directory"
        APP_SERVER_HOME=$(pwd)
        export APP_SERVER_HOME

        if [ "$APP_SERVER_ENV" = "development" ]; then
            if [ -f ".env.development" ]; then
                echo "=> (test-service) Test service - sourcing service .env.development"
                source .env.development
            fi
        fi

        if [ "$APP_SERVER_ENV" = "ci" ]; then
            if [ -f ".env.ci" ]; then
                echo "=> (test-service) Test service - sourcing service .env.ci"
                source .env.ci
            fi
        fi

        if [ -n "$test_function_name" ]; then
            echo "=> (test-service) Test service - ${APP_SERVER_HOME} - function >$test_function_name<"
            go test -v -cover -count 1 -run "$test_function_name" ./... || exit $?
        else
            echo "=> (test-service) Test service - ${APP_SERVER_HOME}"
            go test -cover -count 1 ./... || exit $?
        fi
    fi
}

function test_services {
    base_directory=$1

    current_directory=$PWD
    cd "$base_directory" || exit

    for SERVICE_NAME in *; do
        # Ingoring template
        if [ "$SERVICE_NAME" = "template" ] && [ "$APP_SERVER_ENABLE_TEMPLATE" != 1 ]; then
            echo "=> (test-service) - Skipping service $SERVICE_NAME"
            continue
        fi
        cd "$SERVICE_NAME" || exit
        test_service
        cd - || exit
    done

    cd "$current_directory" || exit
}

# Specific service / All services
test_service_name=""
if [ -n "$1" ]; then
    test_service_name=$1
    shift
    test_function_name=$1
    shift

    echo
    echo "=> (test-service) Testing service ${test_service_name}"
    echo

    source "${BASH_SOURCE%/*}"/env-functions || exit $?
    clear_env || exit $?

    source "${BASH_SOURCE%/*}"/env || exit $?

    cd "service/$test_service_name" || exit
    test_service "${test_function_name}";
    cd - || exit

else

    echo
    echo "=> (test-service) Testing all services"
    echo

    # Service directory list
    test_services "service";

    # Service example directory list
    if [[ "$APP_SERVER_ENABLE_EXAMPLES" == 1 ]]; then
        echo "=> (test-service) Starting example services"
       
        test_services "service/example";
    fi
fi
