#!/usr/bin/env bash

docker run \
	--env APP_SERVER_ENV="ci" \
	--env APP_SERVER_PORT="8084" \
	--env APP_SERVER_LOG_LEVEL="warn" \
	--env APP_SERVER_SCHEMA_PATH="./schema/docs" \
	--env APP_SERVER_JWT_SIGNING_KEY="!notTherealSecretNoob!" \
	--env APP_SERVER_DB_HOST="localhost" \
	--env APP_SERVER_DB_PORT="5432" \
	--env APP_SERVER_DB_NAME="go-mud" \
	--env APP_SERVER_DB_USER="go-mud-user" \
	--env APP_SERVER_DB_PASSWORD="go-mud-pass" \
	go-mud/game-server
