include:
  - template: Security/SAST.gitlab-ci.yml
  - local: "/server/.gitlab-ci.yml"

stages:
  - build
  - test

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, phpcs-security-audit, pmd-apex,
      security-code-scan, sobelow, spotbugs
  stage: test

# All variables are valid for all jobs
variables:
  FF_NETWORK_PER_BUILD: 1
  APP_CLIENT_API_HOST: go-mud-server
  APP_CLIENT_API_PORT: 3000

# Testing the client requires the server and postgres to be running as services.
test-client:
  image: $CI_REGISTRY/alienspaces/go-mud/cirrusci/flutter:stable
  stage: test
  services:
    - name: $CI_REGISTRY/alienspaces/go-mud/go-mud-server:$CI_COMMIT_SHORT_SHA
      alias: go-mud-server
  script:
    - cd client
    - flutter pub get
    - dart ./tool/generate.dart
    - flutter test
  only:
    - develop
    - master
