include:
  - template: Security/SAST.gitlab-ci.yml
  - local: "/backend/.gitlab-ci.yml"
  - local: "/frontend/.gitlab-ci.yml"

stages:
  - test
  - test-backend
  - build-backend
  - test-frontend

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, phpcs-security-audit, pmd-apex,
      security-code-scan, sobelow, spotbugs, eslint, gosec
  stage: test
