include:
  - template: Security/SAST.gitlab-ci.yml
  - local: "/server/.gitlab-ci.yml"
  - local: "/client/.gitlab-ci.yml"

stages:
  - test
  - test-server
  - build-server
  - test-client

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, phpcs-security-audit, pmd-apex,
      security-code-scan, sobelow, spotbugs, eslint, gosec
  stage: test
