test-backend:
  variables:
    POSTGRES_DB: go-mud
    POSTGRES_USER: go-mud-user
    POSTGRES_PASSWORD: go-mud-pass
  image: $CI_REGISTRY/alienspaces/go-mud/golang:1.21.0-alpine3.18
  stage: test-backend
  services:
    - name: $CI_REGISTRY/alienspaces/go-mud/postgres:15.3-alpine3.18
      alias: postgres
  before_script:
    - apk add build-base
    - apk add git
    - apk add bash
    - apk add postgresql-client
  script:
    - cd backend
    - ./tools/test-ci

build-backend:
  image: $CI_REGISTRY/alienspaces/go-mud/docker:23.0.3
  stage: build-backend
  services:
    - name: $CI_REGISTRY/alienspaces/go-mud/docker:23.0.3-dind
      entrypoint: [ "dockerd-entrypoint.sh", "--tls=false" ]
      alias: docker
  before_script:
    - apk add git
    - apk add bash
  script:
    - cd backend
    - ./tools/build
