#!/usr/bin/env bash

# Local development, database setup, with seed data, ready for manual testing

# copy development env
cp .env.development .env

# Environment
source "${BASH_SOURCE%/*}"/env || exit $?

source "${BASH_SOURCE%/*}"/db-start || exit $?

source "${BASH_SOURCE%/*}"/db-migrate-up || exit $?

source "${BASH_SOURCE%/*}"/db-load-seed-data || exit $?
