#!/usr/bin/env bash

# Starts the database, runs database migrations, loads "test" data and starts services

# copy development env
cp .env.development .env

# Environment
source "${BASH_SOURCE%/*}"/env || exit $?

# stop
source "${BASH_SOURCE%/*}"/stop "$1" || exit $?

# start database
source "${BASH_SOURCE%/*}"/db-start "$1" || exit $?

# migrate database
source "${BASH_SOURCE%/*}"/db-migrate-up || exit $?

# load "test" data
source "${BASH_SOURCE%/*}"/db-load-test-data || exit $?

# start services
source "${BASH_SOURCE%/*}"/services-start "$1" || exit $?

# start krakend
source "${BASH_SOURCE%/*}"/krakend-start "$1" || exit $?
