#!/usr/bin/env bash

echo
echo "=> Test core"
echo

# "docker" or "local"
export APP_SERVER_DB_SERVICE=docker
if [ -n "$1" ]; then
    export APP_SERVER_DB_SERVICE=$1
    shift
fi

# Environment
if [ -z "$APP_SERVER_GO_VERSION" ]; then
    source "${BASH_SOURCE%/*}"/env || exit $?
fi

cd core || exit
go test -cover -count 1 ./... || exit $?
cd - || exit
