#!/usr/bin/env bash

# build all services that have been modified
if [ -z "$CI_REGISTRY" ]; then
    CI_REGISTRY="registry.gitlab.com"
fi

if [ -z "$CI_COMMIT_SHORT_SHA" ]; then
    CI_COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
fi

if [ -n "$GITLAB_PERSONAL_TOKEN" ]; then
    docker login registry.gitlab.com -u alienspaces@gmail.com -p "$GITLAB_PERSONAL_TOKEN"
fi

if [ -n "$CI_REGISTRY_USER" ] && [ -n "$CI_REGISTRY_PASSWORD" ]; then
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
fi

# service directory list
shopt -s dotglob
shopt -s nullglob

# Service directory list
SERVICE_BASE_PATH=./service
cd $SERVICE_BASE_PATH || exit
SERVICE_NAMES=(game)
cd - || exit

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    # Ingoring template always
    if [ "$SERVICE_NAME" = "template" ]; then
        echo "=> (build) - Skipping build service $SERVICE_NAME"
        continue
    fi

    echo "=> (build) - Building service $SERVICE_NAME"

    SERVICE_DIR="./service/$SERVICE_NAME"
    echo "Directory: $SERVICE_DIR";
    echo ""

    if [ -f "${SERVICE_DIR}/build/docker/Dockerfile" ]; then
        docker build -f "${SERVICE_DIR}/build/docker/Dockerfile" -t "go-mud/${SERVICE_NAME}-server" .
        docker tag "go-mud/${SERVICE_NAME}-server" "${CI_REGISTRY}/alienspaces/go-mud/${SERVICE_NAME}-server:latest"
        docker push "${CI_REGISTRY}/alienspaces/go-mud/${SERVICE_NAME}-server:latest"
        docker tag "go-mud/${SERVICE_NAME}-server" "${CI_REGISTRY}/alienspaces/go-mud/${SERVICE_NAME}-server:${CI_COMMIT_SHORT_SHA}"
        docker push "${CI_REGISTRY}/alienspaces/go-mud/${SERVICE_NAME}-server:${CI_COMMIT_SHORT_SHA}"
    fi

done


