#!/usr/bin/env bash

if [ -z "$CI_REGISTRY" ]; then
    CI_REGISTRY="registry.gitlab.com"
fi

if [ -z "$CI_COMMIT_SHORT_SHA" ]; then
    CI_COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
fi

docker run \
	--env APP_SERVER_ENV="ci" \
	--env APP_SERVER_PORT="8084" \
	--env APP_SERVER_LOG_LEVEL="warn" \
	--env APP_SERVER_LOG_PRETTY="true" \
	--env APP_SERVER_SCHEMA_PATH="./schema/docs" \
	--env APP_SERVER_JWT_SIGNING_KEY="!notTherealSecretNoob!" \
	--env APP_SERVER_DB_HOST="localhost" \
	--env APP_SERVER_DB_PORT="5432" \
	--env APP_SERVER_DB_NAME="go-mud" \
	--env APP_SERVER_DB_USER="go-mud-user" \
	--env APP_SERVER_DB_PASSWORD="go-mud-pass" \
    --env APP_SERVER_DB_MAX_OPEN_CONNECTIONS="50" \
    --env APP_SERVER_DB_MAX_IDLE_CONNECTIONS="25" \
    --env APP_SERVER_DB_MAX_IDLE_TIME_MINS="15" \
    --env APP_SERVER_TURN_DURATION="2000" \
	--name game-server \
	"${CI_REGISTRY}/alienspaces/go-mud/game-server:${CI_COMMIT_SHORT_SHA}"
