#!/usr/bin/env bash

# DESCRIPTION:
#   Execute ./service unit tests
# USAGE:
#   Test all services
#     ./script/test-service
#   Test specific service
#     ./script/test-service ./service/example/player

echo
echo "=> (test-docker-build-ci) Testing docker build CI"
echo
if [ -n "$1" ]; then
    TEST_SERVICE_NAME=$1
    shift
fi

# Service directory list
SERVICE_BASE_PATH=./service
cd $SERVICE_BASE_PATH || exit
SERVICE_NAMES=(*)
cd - || exit

if [ -z "$CI_COMMIT_SHORT_SHA" ]; then
    CI_COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
fi

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    # Ingoring template always
    if [ "$SERVICE_NAME" = "template" ]; then
        echo "=> (build) - Skipping build service $SERVICE_NAME"
        continue
    fi

    if [ -n "$TEST_SERVICE_NAME" ] && [ "$SERVICE_NAME" !=  "$TEST_SERVICE_NAME" ]; then
        echo "=> (build) - Skipping build service $SERVICE_NAME"
        continue
    fi

    echo "=> (build) - Building service $SERVICE_NAME"

    SERVICE_DIR="./service/$SERVICE_NAME"
    echo "Directory: $SERVICE_DIR";
    echo ""

    if [ -f "${SERVICE_DIR}/build/docker/Dockerfile" ]; then
        docker build -f "${SERVICE_DIR}/build/docker/Dockerfile" -t "go-mud/${SERVICE_NAME}-server" .
        docker tag "go-mud/${SERVICE_NAME}-server" "registry.gitlab.com/alienspaces/go-mud/${SERVICE_NAME}-server:latest"
        docker tag "go-mud/${SERVICE_NAME}-server" "registry.gitlab.com/alienspaces/go-mud/${SERVICE_NAME}-server:${CI_COMMIT_SHORT_SHA}"
    fi

done
