# Testing the server requires postgres to be running as a service.
test-server:
  image: $CI_REGISTRY/alienspaces/go-mud/golang:1.17.2-alpine3.14
  stage: test-server
  services:
    - name: $CI_REGISTRY/alienspaces/go-mud/postgres:12.7-alpine3.14
      alias: postgres
  before_script:
    - apk add build-base
    - apk add git
    - apk add bash
    - apk add postgresql-client
  script:
    - cd server
    - ./script/test-ci

build-server:
  image: docker:19.03.12
  stage: build-server
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add git
    - apk add bash
  script:
    - cd server
    - ./script/build
