test-server:
  variables:
    POSTGRES_DB: go-mud
    POSTGRES_USER: go-mud-user
    POSTGRES_PASSWORD: go-mud-pass
  image: $CI_REGISTRY/alienspaces/go-mud/golang:1.19.2-alpine3.16
  stage: test-server
  services:
    - name: $CI_REGISTRY/alienspaces/go-mud/postgres:13.7-alpine3.16
      alias: postgres
  before_script:
    - apk add build-base
    - apk add git
    - apk add bash
    - apk add postgresql-client
  script:
    - cd server
    - ./script/test-ci

build-server:
  image: $CI_REGISTRY/alienspaces/go-mud/docker:20.10.17
  stage: build-server
  services:
    - name: $CI_REGISTRY/alienspaces/go-mud/docker:20.10.17-dind
      alias: docker
  before_script:
    - apk add git
    - apk add bash
  script:
    - cd server
    - ./script/build
